src/java/controlador/EdificioController.java
package controlador;

import entidades.Edificio;
import controlador.util.JsfUtil;
import controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("edificioController")
@SessionScoped
public class EdificioController implements Serializable {

    @EJB
    private controlador.EdificioFacade ejbFacade;
    private List<Edificio> items = null;
    private Edificio selected;

    public EdificioController() {
    }

    public Edificio getSelected() {
        return selected;
    }

    public void setSelected(Edificio selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private EdificioFacade getFacade() {
        return ejbFacade;
    }

    public Edificio prepareCreate() {
        selected = new Edificio();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("EdificioCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("EdificioUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("EdificioDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Edificio> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Edificio getEdificio(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Edificio> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Edificio> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Edificio.class)
    public static class EdificioControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EdificioController controller = (EdificioController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "edificioController");
            return controller.getEdificio(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Edificio) {
                Edificio o = (Edificio) object;
                return getStringKey(o.getFkEdificio());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Edificio.class.getName()});
                return null;
            }
        }

    }

}

web/edificio/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="EdificioCreateDlg" widgetVar="EdificioCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateEdificioTitle}">
            <h:form id="EdificioCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{edificioController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_fkEdificio}" for="fkEdificio" />
                        <p:inputText id="fkEdificio" value="#{edificioController.selected.fkEdificio}" title="#{bundle.CreateEdificioTitle_fkEdificio}" required="true" requiredMessage="#{bundle.CreateEdificioRequiredMessage_fkEdificio}"/>
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_fkCiudad}" for="fkCiudad" />
                        <p:inputText id="fkCiudad" value="#{edificioController.selected.fkCiudad}" title="#{bundle.CreateEdificioTitle_fkCiudad}" required="true" requiredMessage="#{bundle.CreateEdificioRequiredMessage_fkCiudad}"/>
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_capacidad}" for="capacidad" />
                        <p:inputText id="capacidad" value="#{edificioController.selected.capacidad}" title="#{bundle.CreateEdificioTitle_capacidad}" required="true" requiredMessage="#{bundle.CreateEdificioRequiredMessage_capacidad}"/>
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_codigoPostal}" for="codigoPostal" />
                        <p:inputText id="codigoPostal" value="#{edificioController.selected.codigoPostal}" title="#{bundle.CreateEdificioTitle_codigoPostal}" />
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_edificio}" for="edificio" />
                        <p:selectOneMenu id="edificio" value="#{edificioController.selected.edificio}" >
                            <f:selectItems value="#{edificioController.itemsAvailableSelectOne}"
                                           var="edificioItem"
                                           itemValue="#{edificioItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateEdificioLabel_edificio1}" for="edificio1" />
                        <p:selectOneMenu id="edificio1" value="#{edificioController.selected.edificio1}" required="true" requiredMessage="#{bundle.EditEdificioRequiredMessage_edificio1}">
                            <f:selectItems value="#{edificioController.itemsAvailableSelectOne}"
                                           var="edificio1Item"
                                           itemValue="#{edificio1Item}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{edificioController.create}" value="#{bundle.Save}" update="display,:EdificioListForm:datalist,:growl" oncomplete="handleSubmit(args,'EdificioCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="EdificioCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/edificio/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="EdificioEditDlg" widgetVar="EdificioEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditEdificioTitle}">
            <h:form id="EdificioEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{edificioController.selected != null}">
                        <p:outputLabel value="#{bundle.EditEdificioLabel_fkEdificio}" for="fkEdificio" />
                        <p:inputText id="fkEdificio" value="#{edificioController.selected.fkEdificio}" title="#{bundle.EditEdificioTitle_fkEdificio}" required="true" requiredMessage="#{bundle.EditEdificioRequiredMessage_fkEdificio}"/>
                        <p:outputLabel value="#{bundle.EditEdificioLabel_fkCiudad}" for="fkCiudad" />
                        <p:inputText id="fkCiudad" value="#{edificioController.selected.fkCiudad}" title="#{bundle.EditEdificioTitle_fkCiudad}" required="true" requiredMessage="#{bundle.EditEdificioRequiredMessage_fkCiudad}"/>
                        <p:outputLabel value="#{bundle.EditEdificioLabel_capacidad}" for="capacidad" />
                        <p:inputText id="capacidad" value="#{edificioController.selected.capacidad}" title="#{bundle.EditEdificioTitle_capacidad}" required="true" requiredMessage="#{bundle.EditEdificioRequiredMessage_capacidad}"/>
                        <p:outputLabel value="#{bundle.EditEdificioLabel_codigoPostal}" for="codigoPostal" />
                        <p:inputText id="codigoPostal" value="#{edificioController.selected.codigoPostal}" title="#{bundle.EditEdificioTitle_codigoPostal}" />
                        <p:outputLabel value="#{bundle.EditEdificioLabel_edificio}" for="edificio" />
                        <p:selectOneMenu id="edificio" value="#{edificioController.selected.edificio}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{edificioController.itemsAvailableSelectOne}"
                                           var="edificioItem"
                                           itemValue="#{edificioItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditEdificioLabel_edificio1}" for="edificio1" />
                        <p:selectOneMenu id="edificio1" value="#{edificioController.selected.edificio1}" required="true" requiredMessage="#{bundle.EditEdificioRequiredMessage_edificio1}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{edificioController.itemsAvailableSelectOne}"
                                           var="edificio1Item"
                                           itemValue="#{edificio1Item}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{edificioController.update}" value="#{bundle.Save}" update="display,:EdificioListForm:datalist,:growl" oncomplete="handleSubmit(args, 'EdificioEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="EdificioEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/edificio/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListEdificioTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="EdificioListForm">
                <p:panel header="#{bundle.ListEdificioTitle}">
                    <p:dataTable id="datalist" value="#{edificioController.items}" var="item"
                                 selectionMode="single" selection="#{edificioController.selected}"
                                 paginator="true"
                                 rowKey="#{item.fkEdificio}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_fkEdificio}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkEdificio}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_fkCiudad}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkCiudad}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_capacidad}"/>
                            </f:facet>
                            <h:outputText value="#{item.capacidad}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_codigoPostal}"/>
                            </f:facet>
                            <h:outputText value="#{item.codigoPostal}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_edificio}"/>
                            </f:facet>
                            <h:outputText value="#{item.edificio}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEdificioTitle_edificio1}"/>
                            </f:facet>
                            <h:outputText value="#{item.edificio1}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{edificioController.prepareCreate}" update=":EdificioCreateForm" oncomplete="PF('EdificioCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":EdificioViewForm" oncomplete="PF('EdificioViewDialog').show()" disabled="#{empty edificioController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":EdificioEditForm" oncomplete="PF('EdificioEditDialog').show()" disabled="#{empty edificioController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{edificioController.destroy}" update=":growl,datalist" disabled="#{empty edificioController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/edificio/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="EdificioViewDlg" widgetVar="EdificioViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewEdificioTitle}">
            <h:form id="EdificioViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{edificioController.selected != null}">
                        <h:outputText value="#{bundle.ViewEdificioLabel_fkEdificio}"/>
                        <h:outputText value="#{edificioController.selected.fkEdificio}" title="#{bundle.ViewEdificioTitle_fkEdificio}"/>
                        <h:outputText value="#{bundle.ViewEdificioLabel_fkCiudad}"/>
                        <h:outputText value="#{edificioController.selected.fkCiudad}" title="#{bundle.ViewEdificioTitle_fkCiudad}"/>
                        <h:outputText value="#{bundle.ViewEdificioLabel_capacidad}"/>
                        <h:outputText value="#{edificioController.selected.capacidad}" title="#{bundle.ViewEdificioTitle_capacidad}"/>
                        <h:outputText value="#{bundle.ViewEdificioLabel_codigoPostal}"/>
                        <h:outputText value="#{edificioController.selected.codigoPostal}" title="#{bundle.ViewEdificioTitle_codigoPostal}"/>
                        <h:outputText value="#{bundle.ViewEdificioLabel_edificio}"/>
                        <h:outputText value="#{edificioController.selected.edificio}" title="#{bundle.ViewEdificioTitle_edificio}"/>
                        <h:outputText value="#{bundle.ViewEdificioLabel_edificio1}"/>
                        <h:outputText value="#{edificioController.selected.edificio1}" title="#{bundle.ViewEdificioTitle_edificio1}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="EdificioViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>